### ISSUE TITLE
What data format/types will you be using. 

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#10]
Terms such as "commonly used data formats" need to be defined more clearly for researchers. This tends to be interpreted rather differently depending on the type of research. And a lot of researchers consider proprietary formats as leading or common formats. And the question "Does this format enable sharing and long term arching" is jargon; this will mean very little to most researchers. And if the answer is no, then what?

**Comment by rwwh** [comment]
The question was already restructured a bit; I now also added some more guidance on properties of good formats.
