### ISSUE TITLE
Will you consider re-usability of your data beyond your original purpose?

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#12]
The No answer is rather biased and pejorative. 
You are basically asking people to predict the future. The whole point of future reuse is that you don"t know whether that willl happen, otherwise researchers would probably do it themselves. 
Who decides what is the "bare minimum"
A more encouraging phrasing here would be more helpful.

**Comment by rwwh** [comment]
I have changed the guidance now.
