### ISSUE TITLE
Summary feedback

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#19]
Summary does not provide possible feedback loop to questions or suggestions how to increase what you need for better FAIRness

**Comment by vknaisl** [comment]
Thanks for feedback! 
I created issue in Jira for us and we will plan to implement it in future - https://ds-wizard.atlassian.net/browse/DSW-123. You can subscribe to it and watch the progress.
Just one thing for future - you created a feedback to one question. This should be used for extending / fixing one concrete question to which the  feedback relates to. If you want to give feedback to the Data Stewardship Wizard, please you a form which is placed under this button.

![screenshot 2018-11-26 at 09 41 20](https://user-images.githubusercontent.com/6266374/49002306-8461f700-f15f-11e8-89b0-4cb9fd035095.png)
