### ISSUE TITLE
Random ordering of questions, randomization of reporting

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#20]
If I would like to trick any questionaire, then the easiest way is to go for as longer responses as possible. Have you looked into the social sciences experiences to establish the internal checks for validity of the responses - i.e. randomization of ordering of questions, repeating similar questions, etc.?

**Comment by rwwh** [comment]
I don't think the DSW should be treated like an exam. If the purpose is the benefit of the user/researcher, then tricking is not a problem to fight.
