### ISSUE TITLE
Saving the questionaire

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#24]
After saving of questionaire, I want to see the Summary before leaving it.

**Comment by vknaisl** [comment]
Thanks for feedback! 
It's already issue here - https://ds-wizard.atlassian.net/browse/DSW-117. You can subscribe to it and watch the progress.
Just one thing for future - you created a feedback to one question. This should be used for extending / fixing one concrete question to which the  feedback relates to. If you want to give feedback to the Data Stewardship Wizard, please you a form which is placed under this button.

![screenshot 2018-11-26 at 09 41 20](https://user-images.githubusercontent.com/6266374/49002306-8461f700-f15f-11e8-89b0-4cb9fd035095.png)

**Comment by KarelBerka** [comment]
Sure - put this button inside questionaire as well.

**Comment by vknaisl** [comment]
This button on every screen when you are login. It is placed on bottom left side. I mark it with green rectangle for you on attached screenshot
![screenshot 2018-11-26 at 11 14 45](https://user-images.githubusercontent.com/6266374/49007777-95fdcb80-f16c-11e8-9541-f744135b6871.png)
