### ISSUE TITLE
How will you be doing the integration of different data sources?

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#4]
This is way too detailed and technical; this will go over the heads of many researchers. The attention that "linked data"gets is a little over the top and is it really a desirable solution for most research projects also given the considerable (maintenance) effort needed to realize and maintain linked data. The term "ontologies" means nothing to most researchers. If you answer "no" to all these questions, so what? Researchers could still be doing solid research and good RDM.

**Comment by rwwh** [comment]
I have changed the hierarchy of questions so that this should only come up if it is relevant to the project.
