### ISSUE TITLE
Distinguishing between data and metadata

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#48]
Not all kind of data can be provided "computer readable". What should be machine readable is the metadata. Maybe it´s best to add another question "Do you provide machine readable, standardised metadata to others?" This should not be a follow-up question, since it is possible to keep the data itself closed but publish the metadata. But if the answer is yes, there could be a follow-up "What metadata standard do you use?"

**Comment by rwwh** [comment]
Done.
