### ISSUE TITLE
Physical samples? Please clarify

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#51]
Does the question referr to physical samples like minerals, tissue or construction materials? Or do you mean sample data? If you mean physical materials, follow-up questions are needed, such as "Where are the samples stored?" and "What is the inventory number/registration number/identifier of the sample(s)?" --> This is crucial information to be able to locate and identify the physical samples related to the data.

**Comment by rwwh** [comment]
Clarified and followup questions added
