### ISSUE TITLE
Question seems to be out of place here...

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#52]
The title of this section is "Design of experiment". Perhaps it should be more general "Research design" since not all research is based on experimental data. In that case, this question should be at the very top of this section. In any case, most questions here are actually related to data, but not to the design of the experiment(s) or the research method(s). What is missing are questions like "Is there a general description of the research design? If yes, where? Is is publically accessible? (url, doi...)" In most cases, this information will by crucial to third parties trying to understand and interprete the data correctly.

**Comment by rwwh** [comment]
In version 2.0 we moved all questions to more standard "data life cycle stages". 
I added a question for the link to the project proposal to the administrative chapter.
