### ISSUE TITLE
Can all of your data become completely open immediately?

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#6]
Again, is this really relevant: good documentation and transparancy is more relevant and a typical and more useful answer would be "part of the data can be open immediately" and then define which data can be open immediately. Yes/no options don"t work.

**Comment by rwwh** [comment]
Valid comment: complete openness is useless without FAIR data. However, funders do want to know when data will become available. Since this issue was opened, followup questions have been added under "No" to detail what de  reasons are. I hope this addresses the issue.
