### ISSUE TITLE
FAIR score higher for domain specific repos?

### ISSUE THREAD

**Issue by DSWGlobal** [DSWGlobal/dsw#64]
Why a higher FAIR score for sharing in domain-specific repository, where Findability will be lower perhaps than rather than in a "general purpose" repo like Zenodo, Dataverse etc. - especially for data that could be repurposed for re-use?

**Comment by rwwh** [comment]
Because 
1. domain specific repositories are often offering more functionality
2. primary reuse is likely to be in a field close to the original field, and the domain specific repository is where people would look (I would not search for gene sequences in Zenodo, really in ENA!)

Won't fix.
